test:
	#nosetests tests
	python tests/DataExtractorTest.py

build:
	scripts/build.sh

deploy-refresh-token:
	scripts/deploy-refresh-token.sh

deploy:
	scripts/deploy.sh

undeploy:
	scripts/undeploy.sh

destroy:
	scripts/destroy.sh

docker-local:
	scripts/docker-local.sh

docker-event:
	scripts/docker-event.sh

create-function:
	scripts/create-function.sh

delete-function:
	scripts/delete-function.sh
