test:
	#nosetests tests
	python tests/DataExtractorTest.py

build:
	scripts/build.sh

deploy:
	scripts/deploy.sh

destroy:
	scripts/destroy.sh

docker-local:
	scripts/docker-local.sh

docker-event:
	scripts/docker-event.sh
